name: Run Tests

on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.6.2"

      - name: Run development settings
        run: yarn install

      - name: Run Jest
        run: yarn test
